### ISSUE TITLE
gflags-derive

### ISSUE THREAD

**Issue by nikclayton** [dtolnay/gflags#12]
Hi,

Wanted to let you know about https://crates.io/crates/gflags-derive, as I thought you might be interested.

I wrote this because I want to be able to derive the external configuration interface for a library from a schema that can evolve over time and supports backwards compatibility.

In short, protobuffers.

Turns out the easiest way to do this is to support declaring structs and struct fields as the source of the configuration data (those can be hand-written Rust structs, or structs derived from an external schema like protobuffers), so this is like structopt-for-gflags.

**Comment by dtolnay** [comment]
Neat! Thanks for the link.
