### ISSUE TITLE
Placeholder values can only be idents

### ISSUE THREAD

**Issue by nikclayton** [dtolnay/gflags#14]
This:

```rust
gflags::define! {
    /// Address to listen on
    -a, --addr <HOST:PORT> = "localhost:8080"
}
```

doesn't work, as `HOST:PORT` can't be parsed as an ident.

**Comment by dtolnay** [comment]
I would accept a PR to make this work, or alternatively `--addr <"HOST:PORT">`.

**Comment by nikclayton** [comment]
String in all cases (that would be a breaking change, and I've got code that does that), or only where necessary?

**Comment by dtolnay** [comment]
I would want it to keep working with ident, too.
