### ISSUE TITLE
variables should be prepended with FLAGS_ e.g. FLAGS_help

### ISSUE THREAD

**Issue by glalonde** [dtolnay/gflags#3]
otherwise it seems you run into issues instantly with flag names shadowing internal variable names.

**Comment by dtolnay** [comment]
Good call, the current names are likely to conflict with variables. How about using the uppercase of the flag name as the variable for accessing the flag? That would match the naming convention for globals in Rust.

```rust
gflags::define! {
    --print-args = false
}

fn main() {
    let args = gflags::parse();

    if PRINT_ARGS.flag {
        println!("args = {:?}", args);
    }
}
```

**Comment by glalonde** [comment]
Definitely better. Honestly, I still think collisions would be too likely. Adding something like `FLAGS_` on the front is nice because nobody will _want_ to use this as an internal variable name. Whereas someone could conceivably want to use `ROWS` or `COLS` or `NUM_ITERS` as normal globals, but will then have to decide whether to change their internal vars or their command line interface if they're to mean different things. idk, I personally like the gflags UX where the difference between a flag and a normal global is impossible to ignore, but I have no idea what is idiomatic in rust, so maybe it doesn't fit.

**Comment by dtolnay** [comment]
Yep, `FLAGS_num_iters` is slick. The limiting factor is going to be that in the Rust implementation we require a period when accessing a flag to force a deref. Without a period the flag would be a mutable static which is unsafe to access in general. And something with both a FLAGS_ prefix and a period like `FLAGS_num_iters.value` is relatively verbose.

**Comment by glalonde** [comment]
okay, that makes sense.
